### ISSUE TITLE
Users can join an event multiple times and be registered more than once

### ISSUE THREAD

**Issue by fizzlepuppy** [sbrocket/failsafe#6]
- Tapping the same option twice will duplicate the registration for that user  in that option.
- Tapping a different option when already registered does not switch registration types.
- Tapping Leave will delete all registrations.

**Comment by sbrocket** [comment]
This is actually a debugging feature that’s enabled by flag. I’ll switch it off when I start running the prod bot and fork off a dev bot instance.
