### ISSUE TITLE
Some events are missing activity options 

### ISSUE THREAD

**Issue by fizzlepuppy** [sbrocket/failsafe#8]
Gambit needs to include…
- Playlist
- Custom

PVP is missing…
- Custom
- Rotating (to cover momentum control and other modes)

There’s no way to make an event for a storyline mission, perhaps the exotic category could be reworked to include missions or to include a custom option.

Other needs…
- A way to distinguish between master (for things like 100k) and GM nightfalls
- Maybe this is where missions go

**Comment by sbrocket** [comment]
So there's a custom category (`/lfg create custom`) that's intended to be a catch-all for activities that are uncommon enough that it didn't feel they warranted expanding the list (like private Gambit). Details like master vs GM nightfalls seem like something that's well-handled through the event description.

The downside to custom is that, like Charlemagne, it doesn't match any filters so it would only show up in an "all events" channel. If that becomes an issue (like we're using it a lot) I can find a way to improve that.

Crucible definitely needs a private match option; added. I'm on the fence with rotating crucible types...I think custom works OK for that, plus the rotating types all have different team sizes anyway.

Then for other PvE things...I hadn't added these yet, but I'd intended to add them under Other if needed. I'm not sure I like "Other" though, it's probably confusing...maybe that should merge with "Exotic Quest" into a general "PvE" category.

**Comment by sbrocket** [comment]
Ok, I merged "Exotic Quest" and "Other" into a general "PvE" category, and also added "Other PvP" and "Other PvE" activities so that those get filtered correctly. And then of course there's the "/lfg create custom" catch-all.

Here's the new list:
```
define_activities! {
    VaultOfGlass: ("Vault of Glass", "vog", Raid, 6),
    DeepStoneCrypt: ("Deep Stone Crypt", "dsc", Raid, 6),
    GardenOfSalvation: ("Garden of Salvation", "gos", Raid, 6),
    LastWish: ("Last Wish", "lw", Raid, 6),
    Prophecy: ("Prophecy", "proph", Dungeon, 3),
    PitOfHeresy: ("Pit of Heresy", "pit", Dungeon, 3),
    ShatteredThrone: ("Shattered Throne", "throne", Dungeon, 3),
    IronBanner: ("Iron Banner", "ib", Crucible, 6),
    TrialsOfOsiris: ("Trials of Osiris", "trials", Crucible, 4),
    Quickplay: ("Quickplay", "quick", Crucible, 4),
    Competitive: ("Competitive", "comp", Crucible, 4),
    PrivateMatch: ("Private Match", "priv", Crucible, 6),
    OtherPvP: ("Other PvP", "pvp", Crucible, 6),
    Gambit: ("Gambit", "gambit", Gambit, 4),
    Grandmaster: ("Grandmaster Nightfall", "gm", PvE, 3),
    Nightfall: ("Nightfall", "nf", PvE, 3),
    Harbinger: ("Harbinger", "harb", PvE, 3),
    Presage: ("Presage", "pres", PvE, 3),
    Story: ("Story Missions", "story", PvE, 3),
    OtherPvE: ("Other PvE", "pve", PvE, 3),
    Override: ("Override", "override", Seasonal, 6),
    Battleground: ("Battleground", "battle", Seasonal, 3),
    WrathbornHunt: ("Wrathborn Hunt", "hunt", Seasonal, 3),
    Custom: ("Custom", "cust", Custom, 6),
}
```

Anything else you'd add?

**Comment by fizzlepuppy** [comment]
LGTM
